/**
 * Redux barrel exports.
 */
export { default as store, persistor } from './store'

export { default as authReducer } from './slices/authSlice'
export { default as uiReducer } from './slices/uiSlice'
export { default as wishlistReducer } from './slices/wishlistSlice'
export { default as bookingReducer } from './slices/bookingSlice'
export { default as notificationReducer } from './slices/notificationSlice'
export { default as checkoutReducer } from './slices/checkoutSlice'
export { default as paymentReducer } from './slices/paymentSlice'
export { default as couponReducer } from './slices/couponSlice'
export { default as tripReducer } from './slices/tripSlice'
export { default as dashboardReducer } from './slices/dashboardSlice'
export { default as profileReducer } from './slices/profileSlice'
export { default as walletReducer } from './slices/walletSlice'
export { default as supportReducer } from './slices/supportSlice'
export { default as settingsReducer } from './slices/settingsSlice'

export * from './slices/authSlice'
export * from './slices/uiSlice'
export * from './slices/wishlistSlice'
export * from './slices/bookingSlice'
export * from './slices/notificationSlice'
export * from './slices/checkoutSlice'
export * from './slices/paymentSlice'
export * from './slices/couponSlice'
export * from './slices/tripSlice'
export * from './slices/dashboardSlice'
export * from './slices/profileSlice'
export * from './slices/walletSlice'
export * from './slices/supportSlice'
export * from './slices/settingsSlice'
